import type { BillingType, ServiceCategory } from "./schema";

export interface SeedService {
  category: ServiceCategory;
  titleHe: string;
  titleRu: string;
  descriptionHe?: string;
  descriptionRu?: string;
  keywords: string[];
  defaultPrice: number;
  billingType: BillingType;
  unit: string;
  markupPercent?: number;
  includedHours?: number;
  sku?: string;
}

/** Rich IT Solutions default service catalog — six core categories. */
export const seedServices: SeedService[] = [
  // 1. Network Infrastructure — תשתיות תקשורת
  {
    category: "network_infrastructure",
    titleHe: "תכנון ותשתית LAN/סיבים אופטיים",
    titleRu: "Проектирование LAN/оптоволоконной инфраструктуры",
    descriptionHe: "תכנון וביצוע רשת מקומית ותשתית סיבים אופטיים למבנה משרדי/תעשייתי.",
    keywords: ["lan", "fiber", "סיבים", "תקשורת", "оптоволокно", "лан", "network design"],
    defaultPrice: 350,
    billingType: "hourly",
    unit: "hour",
    sku: "NET-001",
  },
  {
    category: "network_infrastructure",
    titleHe: "סקר וייעול רשת אלחוטית (Wi-Fi Survey)",
    titleRu: "Обследование и оптимизация Wi-Fi сети",
    descriptionHe: "מיפוי כיסוי אלחוטי, איתור נקודות מתות והמלצות למיקום נקודות גישה.",
    keywords: ["wifi survey", "סקר wifi", "כיסוי אלחוטי", "обследование wifi", "точки доступа"],
    defaultPrice: 900,
    billingType: "fixed",
    unit: "project",
    sku: "NET-002",
  },
  {
    category: "network_infrastructure",
    titleHe: "הקמת VLAN וניתוב (Routing)",
    titleRu: "Настройка VLAN и маршрутизации",
    descriptionHe: "הגדרת VLAN, ניתוב בין רשתות ומדיניות אבטחת רשת.",
    keywords: ["vlan", "routing", "ניתוב", "маршрутизация", "вилан"],
    defaultPrice: 380,
    billingType: "hourly",
    unit: "hour",
    sku: "NET-003",
  },
  {
    category: "network_infrastructure",
    titleHe: "התקנה והגדרה — Cisco",
    titleRu: "Установка и настройка — Cisco",
    keywords: ["cisco", "סיסקו", "switch", "מתג"],
    defaultPrice: 420,
    billingType: "hourly",
    unit: "hour",
    sku: "NET-004",
  },
  {
    category: "network_infrastructure",
    titleHe: "התקנה והגדרה — Aruba",
    titleRu: "Установка и настройка — Aruba",
    keywords: ["aruba", "ארובה"],
    defaultPrice: 420,
    billingType: "hourly",
    unit: "hour",
    sku: "NET-005",
  },
  {
    category: "network_infrastructure",
    titleHe: "התקנה והגדרה — Fortinet (רשת)",
    titleRu: "Установка и настройка — Fortinet (сеть)",
    keywords: ["fortinet", "fortigate", "פורטינט"],
    defaultPrice: 420,
    billingType: "hourly",
    unit: "hour",
    sku: "NET-006",
  },
  {
    category: "network_infrastructure",
    titleHe: "התקנה והגדרה — Ubiquiti UniFi",
    titleRu: "Установка и настройка — Ubiquiti UniFi",
    keywords: ["ubiquiti", "unifi", "יוביקיטי"],
    defaultPrice: 350,
    billingType: "hourly",
    unit: "hour",
    sku: "NET-007",
  },

  // 2. Server Infrastructure & Virtualization — תשתיות שרתים ווירטואליזציה
  {
    category: "server_infrastructure",
    titleHe: "הקמת סביבת וירטואליזציה — VMware",
    titleRu: "Развёртывание виртуализации — VMware",
    keywords: ["vmware", "esxi", "vsphere", "וירטואליזציה", "виртуализация"],
    defaultPrice: 480,
    billingType: "hourly",
    unit: "hour",
    sku: "SRV-001",
  },
  {
    category: "server_infrastructure",
    titleHe: "הקמת סביבת וירטואליזציה — Hyper-V",
    titleRu: "Развёртывание виртуализации — Hyper-V",
    keywords: ["hyper-v", "hyperv", "מיקרוסופט"],
    defaultPrice: 450,
    billingType: "hourly",
    unit: "hour",
    sku: "SRV-002",
  },
  {
    category: "server_infrastructure",
    titleHe: "הקמת סביבת וירטואליזציה — Proxmox",
    titleRu: "Развёртывание виртуализации — Proxmox",
    keywords: ["proxmox", "פרוקסמוקס", "kvm"],
    defaultPrice: 420,
    billingType: "hourly",
    unit: "hour",
    sku: "SRV-003",
  },
  {
    category: "server_infrastructure",
    titleHe: "הקמת והגדרת Active Directory",
    titleRu: "Развёртывание и настройка Active Directory",
    keywords: ["active directory", "ad", "domain controller", "דומיין", "домен"],
    defaultPrice: 480,
    billingType: "hourly",
    unit: "hour",
    sku: "SRV-004",
  },
  {
    category: "server_infrastructure",
    titleHe: "הקמת Microsoft 365 / Google Workspace",
    titleRu: "Настройка Microsoft 365 / Google Workspace",
    keywords: ["m365", "office 365", "google workspace", "מייל ארגוני", "почта"],
    defaultPrice: 400,
    billingType: "hourly",
    unit: "hour",
    sku: "SRV-005",
  },
  {
    category: "server_infrastructure",
    titleHe: "הקמת מערך גיבויים — Acronis",
    titleRu: "Настройка резервного копирования — Acronis",
    keywords: ["acronis", "backup", "גיבוי", "резервное копирование"],
    defaultPrice: 380,
    billingType: "hourly",
    unit: "hour",
    sku: "SRV-006",
  },
  {
    category: "server_infrastructure",
    titleHe: "הקמת מערך גיבויים — Synology NAS",
    titleRu: "Настройка резервного копирования — Synology NAS",
    keywords: ["synology", "nas", "סינולוג'י", "гибой", "хранилище"],
    defaultPrice: 380,
    billingType: "hourly",
    unit: "hour",
    sku: "SRV-007",
  },

  // 3. Cybersecurity & EDR — אבטחת מידע וסייבר
  {
    category: "cybersecurity",
    titleHe: "הקמה והגדרת NGFW — Check Point",
    titleRu: "Внедрение и настройка NGFW — Check Point",
    keywords: ["check point", "checkpoint", "צ'ק פוינט", "ngfw", "firewall", "פיירוול"],
    defaultPrice: 550,
    billingType: "hourly",
    unit: "hour",
    sku: "SEC-001",
  },
  {
    category: "cybersecurity",
    titleHe: "הקמה והגדרת NGFW — Fortinet",
    titleRu: "Внедрение и настройка NGFW — Fortinet",
    keywords: ["fortinet", "fortigate", "פורטיגייט", "ngfw"],
    defaultPrice: 550,
    billingType: "hourly",
    unit: "hour",
    sku: "SEC-002",
  },
  {
    category: "cybersecurity",
    titleHe: "פריסת EDR — SentinelOne",
    titleRu: "Внедрение EDR — SentinelOne",
    keywords: ["sentinelone", "sentinel one", "edr", "סנטינל"],
    defaultPrice: 500,
    billingType: "hourly",
    unit: "hour",
    sku: "SEC-003",
  },
  {
    category: "cybersecurity",
    titleHe: "פריסת EDR — CrowdStrike",
    titleRu: "Внедрение EDR — CrowdStrike",
    keywords: ["crowdstrike", "קראודסטרייק", "edr", "falcon"],
    defaultPrice: 500,
    billingType: "hourly",
    unit: "hour",
    sku: "SEC-004",
  },
  {
    category: "cybersecurity",
    titleHe: "הפרדת רשתות (Network Segmentation)",
    titleRu: "Сегментация сети",
    keywords: ["segmentation", "הפרדת רשתות", "сегментация"],
    defaultPrice: 480,
    billingType: "hourly",
    unit: "hour",
    sku: "SEC-005",
  },
  {
    category: "cybersecurity",
    titleHe: "מבדק חדירה וסקר אבטחה (Penetration Test)",
    titleRu: "Тест на проникновение и аудит безопасности",
    keywords: ["pentest", "penetration test", "מבדק חדירה", "аудит безопасности", "пентест"],
    defaultPrice: 6500,
    billingType: "fixed",
    unit: "project",
    sku: "SEC-006",
  },
  {
    category: "cybersecurity",
    titleHe: "סקר אבטחת מידע וממצאים (Security Audit)",
    titleRu: "Аудит информационной безопасности",
    keywords: ["security audit", "סקר אבטחה", "аудит"],
    defaultPrice: 3200,
    billingType: "fixed",
    unit: "project",
    sku: "SEC-007",
  },

  // 4. Physical Security — מערכות ביטחון
  {
    category: "physical_security",
    titleHe: "התקנת מצלמות אבטחה — Axis",
    titleRu: "Установка камер видеонаблюдения — Axis",
    keywords: ["axis", "cctv", "מצלמות", "видеонаблюдение"],
    defaultPrice: 450,
    billingType: "hourly",
    unit: "hour",
    sku: "PHY-001",
  },
  {
    category: "physical_security",
    titleHe: "התקנת מצלמות אבטחה — Hikvision",
    titleRu: "Установка камер видеонаблюдения — Hikvision",
    keywords: ["hikvision", "cctv", "מצלמות", "видеонаблюдение"],
    defaultPrice: 380,
    billingType: "hourly",
    unit: "hour",
    sku: "PHY-002",
  },
  {
    category: "physical_security",
    titleHe: "אספקה והתקנת מצלמת IP",
    titleRu: "Поставка и установка IP-камеры",
    keywords: ["מצלמת ip", "camera", "ip camera", "камера"],
    defaultPrice: 850,
    billingType: "hardware_markup",
    unit: "device",
    markupPercent: 20,
    sku: "PHY-003",
  },
  {
    category: "physical_security",
    titleHe: "מערכת אזעקה IP/GSM — Ajax",
    titleRu: "Охранная сигнализация IP/GSM — Ajax",
    keywords: ["ajax", "אלארם", "אזעקה", "сигнализация"],
    defaultPrice: 420,
    billingType: "hourly",
    unit: "hour",
    sku: "PHY-004",
  },
  {
    category: "physical_security",
    titleHe: "מערכת אזעקה IP/GSM — Risco",
    titleRu: "Охранная сигнализация IP/GSM — Risco",
    keywords: ["risco", "ריסקו", "אזעקה"],
    defaultPrice: 420,
    billingType: "hourly",
    unit: "hour",
    sku: "PHY-005",
  },
  {
    category: "physical_security",
    titleHe: "בקרת כניסה — Suprema",
    titleRu: "Контроль доступа — Suprema",
    keywords: ["suprema", "בקרת כניסה", "access control", "контроль доступа"],
    defaultPrice: 480,
    billingType: "hourly",
    unit: "hour",
    sku: "PHY-006",
  },
  {
    category: "physical_security",
    titleHe: "בקרת כניסה — HID",
    titleRu: "Контроль доступа — HID",
    keywords: ["hid", "בקרת כניסה", "access control"],
    defaultPrice: 480,
    billingType: "hourly",
    unit: "hour",
    sku: "PHY-007",
  },

  // 5. Low Voltage & Engineering — עבודות תשתית ומתח נמוך
  {
    category: "low_voltage",
    titleHe: "סידור תשתית כבילה — Cat6A",
    titleRu: "Прокладка кабельной инфраструктуры — Cat6A",
    keywords: ["cat6a", "כבילה", "кабель", "структурированная кабельная система"],
    defaultPrice: 45,
    billingType: "hardware_markup",
    unit: "meter",
    markupPercent: 15,
    sku: "LV-001",
  },
  {
    category: "low_voltage",
    titleHe: "סידור תשתית כבילה — Cat7",
    titleRu: "Прокладка кабельной инфраструктуры — Cat7",
    keywords: ["cat7", "כבילה", "кабель"],
    defaultPrice: 60,
    billingType: "hardware_markup",
    unit: "meter",
    markupPercent: 15,
    sku: "LV-002",
  },
  {
    category: "low_voltage",
    titleHe: "בדיקת תקשורת ואישור (Fluke Test)",
    titleRu: "Сертификация кабельной сети (Fluke Test)",
    keywords: ["fluke", "בדיקת רשת", "сертификация кабеля"],
    defaultPrice: 35,
    billingType: "fixed",
    unit: "point",
    sku: "LV-003",
  },
  {
    category: "low_voltage",
    titleHe: "תכנון ואספקת UPS ו-PDU",
    titleRu: "Проектирование и поставка UPS и PDU",
    keywords: ["ups", "pdu", "גיבוי חשמל", "ибп"],
    defaultPrice: 1200,
    billingType: "hardware_markup",
    unit: "unit",
    markupPercent: 18,
    sku: "LV-004",
  },
  {
    category: "low_voltage",
    titleHe: "הרכבת ארון תקשורת (Server Rack)",
    titleRu: "Монтаж серверной стойки",
    keywords: ["rack", "ארון תקשורת", "стойка", "серверная стойка"],
    defaultPrice: 900,
    billingType: "fixed",
    unit: "unit",
    sku: "LV-005",
  },

  // 6. Managed IT & Support — שירות ותמיכה מנוהלים
  {
    category: "managed_it",
    titleHe: "ריטיינר חודשי — 10 שעות",
    titleRu: "Ежемесячный абонемент — 10 часов",
    descriptionHe: "בנק שעות חודשי לתמיכה שוטפת, מרוחקת ובאתר הלקוח.",
    keywords: ["ריטיינר", "בנק שעות", "абонемент", "retainer"],
    defaultPrice: 2400,
    billingType: "retainer",
    unit: "month",
    includedHours: 10,
    sku: "MSP-001",
  },
  {
    category: "managed_it",
    titleHe: "ריטיינר חודשי — 20 שעות",
    titleRu: "Ежемесячный абонемент — 20 часов",
    keywords: ["ריטיינר", "בנק שעות", "абонемент"],
    defaultPrice: 4400,
    billingType: "retainer",
    unit: "month",
    includedHours: 20,
    sku: "MSP-002",
  },
  {
    category: "managed_it",
    titleHe: "ריטיינר חודשי — 40 שעות",
    titleRu: "Ежемесячный абонемент — 40 часов",
    keywords: ["ריטיינר", "בנק שעות", "абонемент"],
    defaultPrice: 8000,
    billingType: "retainer",
    unit: "month",
    includedHours: 40,
    sku: "MSP-003",
  },
  {
    category: "managed_it",
    titleHe: "תמיכה טכנית באתר הלקוח (On-site)",
    titleRu: "Техническая поддержка на месте (выезд)",
    keywords: ["on-site", "ביקור באתר", "выезд", "поддержка"],
    defaultPrice: 350,
    billingType: "hourly",
    unit: "hour",
    sku: "MSP-004",
  },
  {
    category: "managed_it",
    titleHe: "תמיכה טכנית מרחוק (Remote)",
    titleRu: "Удалённая техническая поддержка",
    keywords: ["remote support", "תמיכה מרחוק", "удалённая поддержка"],
    defaultPrice: 280,
    billingType: "hourly",
    unit: "hour",
    sku: "MSP-005",
  },
  {
    category: "managed_it",
    titleHe: "הגדרת הסכם רמת שירות (SLA)",
    titleRu: "Настройка соглашения об уровне обслуживания (SLA)",
    keywords: ["sla", "רמת שירות", "соглашение об уровне обслуживания"],
    defaultPrice: 1500,
    billingType: "fixed",
    unit: "project",
    sku: "MSP-006",
  },
  {
    category: "managed_it",
    titleHe: "שירותי DevOps וענן",
    titleRu: "DevOps и облачные услуги",
    keywords: ["devops", "cloud", "ענן", "облако", "aws", "azure", "gcp"],
    defaultPrice: 420,
    billingType: "hourly",
    unit: "hour",
    sku: "MSP-007",
  },
];
